### ISSUE TITLE
Update Crates.io version

### ISSUE THREAD

**Issue by Woonters** [shssoichiro/ffmpeg-the-third#90]
The crates.io version is quite far behind at this point and from trying to get another library to compile it might even be so far back it can't work correctly. If any work is needed to be done for this I'd be happy to volunteer some time

**Comment by FreezyLemon** [comment]
The release was held back on purpose since we planned (and are still expecting more) breaking changes while we rework parts of the library, including big changes to the public API. 

> from trying to get another library to compile it might even be so far back it can't work correctly. 

Can you tell us what doesn't work? If there's a big problem with 2.0.1 we could always patch it, or just release current master as 3.0. We just wanted to avoid releasing a new major version every 4 weeks.

**Comment by Woonters** [comment]
Sorry was mistaken, the crate I was trying to fix had a missing feature "non-exhaustive-enums" which explains the compile errors!
